/**
 * The data-set inventory of a MOCK scenario (`?mock=1`, or when src/scenario is unavailable; see mockScenario.ts), so
 * the Data sets screen works in mock mode with the same records and summary as a real build. It is honest about mock
 * mode: the terrain and canopy are the real bundled files the mock read (bytes measured by a request ledger), and
 * everything the mock fabricates (vegetation, fire history, fuel, weather, drought, upper air) is a 'fallback' with
 * origin 'synthetic' and says so. Statistics come from the mock's real grids (scenario/datasetStats.ts).
 *
 * For realistic records of real builds use the fixtures in tests/fixtures/datasets/ (katoomba-bundled.json,
 * live-nondemo.json, offline-synthetic.json).
 */
import { summariseDatasets, type DatasetOrigin, type DatasetRecord, type DatasetSummary } from '../core/datasets';
import type { ScenarioData } from '../core/types';
import type { DatasetLedger } from '../data';
import { canopyStats, fuelStats, terrainStats, weatherStats } from '../scenario/datasetStats';
import { workingMemoryForScenario } from '../scenario/memoryModel';
import { ATTRIBUTION, LICENCES, PROVIDERS, extentOf, sizesOf, skeleton, sumTotals, vintageFor } from '../scenario/recordKit';
import type { ScenarioRequest } from '../scenario/request';

export interface MockDatasetsInput {
  scenario: ScenarioData;
  req: ScenarioRequest;
  ledger: DatasetLedger;
  /** The terrain was generated because no real elevation could be read. */
  terrainSynthetic: boolean;
  /** The bundled canopy raster was read. */
  canopy: boolean;
  startedAt: number;
  warnings: readonly string[];
}

const MOCK = 'Mock mode (for trying the interface): ';

const originOfTag = (ledger: DatasetLedger, tag: string): DatasetOrigin => {
  const t = ledger.totals(tag);
  if (t.newestNetworkAt > 0) return 'live'; // a successful download (failed attempts are on the ledger too)
  if (t.bySource.cache + t.bySource.stale > 0) return 'cache';
  if (t.bySource.pack > 0) return 'area-pack';
  return 'bundled';
};

/** Records and summary of a mock scenario. */
export function mockDatasets(i: MockDatasetsInput): { datasets: DatasetRecord[]; summary: DatasetSummary } {
  const s = i.scenario;
  const now = Date.now();
  const extent = extentOf(s.origin, s.extent);
  const g = s.terrain.grid;
  const model = { resolutionM: g.cellSize, width: g.nx, height: g.ny, cells: g.nx * g.ny };
  const synthetic = (id: string, role: DatasetRecord['role'], title: string, what: string, why: string, reason: string, stats: DatasetRecord['stats'] = []): DatasetRecord =>
    skeleton({
      id,
      role,
      title,
      what,
      why,
      provider: PROVIDERS.app,
      licence: LICENCES.app,
      attribution: ATTRIBUTION.app,
      format: 'Generated by the mock',
      kind: 'synthetic',
      status: 'fallback',
      origin: 'synthetic',
      fallbackReason: `${MOCK}${reason}`,
      vintage: { retrievedAt: now, retrievedBasis: 'generated' },
      extent,
      coverage: { fraction: 0, filledBy: 'mock data', filledOrigin: 'synthetic' },
      model: { ...model, resampling: 'generated' },
      sizes: { transferredBytes: 0, networkBytes: 0, cachedBytes: 0, requests: 0 },
      stats,
      evidence: { level: 'synthetic', note: 'Fabricated by the mock scenario builder; not data.' },
      limitations: ['Mock data: use the real app (without ?mock=1) for real data sets.'],
    });
  const records: DatasetRecord[] = [];

  // ── terrain (real bundled or downloaded elevation, or generated) ──
  const tt = sumTotals(i.ledger, ['terrain']);
  const ts = terrainStats(s.terrain);
  if (i.terrainSynthetic) records.push(synthetic('terrain', 'terrain', 'Ground height', 'Made-up ground shape.', 'Slope and aspect for the fire.', 'no real elevation could be read, so a made-up escarpment is used.', ts.stats));
  else {
    const origin = originOfTag(i.ledger, 'terrain');
    records.push(
      skeleton({
        id: 'terrain',
        role: 'terrain',
        title: 'Ground height',
        what: 'Real elevation read by the mock builder (bundled demo files or terrain tiles).',
        why: 'Slope and aspect for the mock fire.',
        provider: origin === 'bundled' ? PROVIDERS.spatial : PROVIDERS.awsTerrain,
        licence: origin === 'bundled' ? LICENCES.ccBy : LICENCES.publicDomain,
        attribution: origin === 'bundled' ? ATTRIBUTION.spatial : ATTRIBUTION.terrarium,
        format: s.terrain.source,
        kind: 'raster',
        status: 'used',
        origin,
        originDetail: s.terrain.source,
        vintage: vintageFor(origin, tt, now),
        extent,
        coverage: { fraction: 1 },
        model: { ...model, resampling: 'bilinear' },
        sizes: sizesOf(tt),
        stats: ts.stats,
        ...(ts.distribution ? { distribution: ts.distribution } : {}),
        layer: { overlay: 'elevation', layerId: 'elevation' },
        evidence: { level: 'measured', note: 'Real elevation; everything built on it in mock mode is fabricated.' },
        limitations: ['Mock mode reads the terrain at the fire-grid resolution only.'],
      }),
    );
  }
  records.push(
    skeleton({
      id: 'imagery',
      role: 'imagery',
      title: 'Aerial photo',
      what: 'Aerial photographs of the demo sites.',
      why: 'Display only.',
      provider: PROVIDERS.spatial,
      licence: LICENCES.ccBy,
      attribution: ATTRIBUTION.imagery,
      format: '-',
      kind: 'raster',
      status: 'skipped',
      origin: 'none',
      fallbackReason: `${MOCK}the photo is not part of the mock inventory.`,
      vintage: { retrievedAt: 0, retrievedBasis: 'unknown' },
      coverage: { fraction: 0 },
      sizes: { transferredBytes: 0, networkBytes: 0, cachedBytes: 0, requests: 0 },
      evidence: { level: 'measured', note: 'Not recorded in mock mode.' },
    }),
  );
  // ── canopy (real bundled raster or type defaults) ──
  const ct = sumTotals(i.ledger, ['canopy-height']);
  if (i.canopy) {
    const cs = canopyStats(s.fuel);
    records.push(
      skeleton({
        id: 'canopy-height',
        role: 'canopy',
        title: 'Tree canopy height',
        what: 'The bundled Meta and WRI canopy height raster, read by the mock builder.',
        why: 'Tree heights for the mock fuel.',
        provider: PROVIDERS.meta,
        licence: LICENCES.ccBy,
        attribution: ATTRIBUTION.meta,
        format: 'PNG, bundled',
        kind: 'raster',
        status: 'used',
        origin: originOfTag(i.ledger, 'canopy-height'),
        vintage: vintageFor('bundled', ct, now, { capturedOn: '2016' }),
        extent,
        coverage: { fraction: 1 },
        model: { ...model, resampling: 'area-average' },
        sizes: sizesOf(ct),
        stats: cs.stats,
        evidence: { level: 'modelled', note: 'Predicted from imagery by a neural network trained on airborne LiDAR.' },
      }),
    );
  } else records.push(synthetic('canopy-height', 'canopy', 'Tree canopy height', 'Tree heights estimated from the terrain.', 'Tree heights for the mock fuel.', 'no canopy raster here: heights are estimated.'));

  const fs = fuelStats(s.fuel);
  records.push(synthetic('vegetation-svtm', 'vegetation', 'Vegetation map', 'Fuel types fabricated from landform, canopy and elevation.', 'The fuel class of every cell.', 'no vegetation map is read; fuel types are fabricated.', fs.stats.slice(0, 5)));
  records.push(synthetic('fire-history', 'fireHistory', 'Fire history', 'Fabricated times since fire.', 'How much fuel has built up.', 'no fire history is read; times since fire are fabricated.'));
  records.push(synthetic('fuel-derived', 'fuel', 'Fuel map', 'The mock fuel map.', 'The direct input of the fire model.', 'the fuel map is fabricated.', fs.stats));
  const ws = weatherStats(s.weather, s.startTime, s.duration);
  records.push(synthetic('weather', 'weather', 'Weather', 'A fabricated weather series that follows the chosen mode.', 'Wind, temperature and humidity for the run.', 'the weather is fabricated.', ws.stats));
  records.push(synthetic('upper-air', 'upperAir', 'Upper-air profile', 'No upper-air data.', 'Stability and the wind aloft.', 'no upper-air data.'));
  records.push(synthetic('drought-history', 'weather', 'Rainfall history and drought', 'Fabricated drought values.', 'How dry the deep fuel is.', 'no rainfall history is read.'));
  for (const [id, title] of [
    ['roads', 'Roads and tracks'],
    ['fire-trails', 'Fire trails'],
    ['homes', 'Homes (address points)'],
    ['zones', 'Residential and built-up zones'],
    ['place-names', 'Place names'],
  ] as const) {
    records.push(
      skeleton({
        id,
        role: 'context',
        title,
        what: 'NSW map data (not loaded in mock mode).',
        why: 'Display only.',
        provider: PROVIDERS.spatial,
        licence: LICENCES.ccBy,
        attribution: '© Spatial Services NSW',
        format: '-',
        kind: 'vector',
        status: 'unavailable',
        origin: 'none',
        fallbackReason: `${MOCK}roads, homes and places are not loaded.`,
        vintage: { retrievedAt: 0, retrievedBasis: 'unknown' },
        coverage: { fraction: 0 },
        sizes: { transferredBytes: 0, networkBytes: 0, cachedBytes: 0, requests: 0 },
        evidence: { level: 'measured', note: 'Not loaded in mock mode.' },
      }),
    );
  }
  records.push(
    skeleton({
      id: 'user-edits',
      role: 'user',
      title: 'Your input',
      what: 'Everything you typed, marked or painted.',
      why: 'Your changes override the data.',
      provider: PROVIDERS.user,
      licence: LICENCES.user,
      attribution: 'Entered by the user',
      format: 'Scenario edits (JSON)',
      kind: 'table',
      status: 'skipped',
      origin: 'none',
      vintage: { retrievedAt: now, retrievedBasis: 'generated' },
      coverage: { fraction: 0 },
      sizes: { transferredBytes: 0, networkBytes: 0, cachedBytes: 0, requests: 0 },
      evidence: { level: 'assumed', note: 'Whatever you enter is taken as true.' },
    }),
  );
  const summary = summariseDatasets(records, {
    scenarioId: s.id,
    scenarioName: s.name,
    seed: s.options.seed,
    builtAt: now,
    buildDurationMs: Math.max(0, now - i.startedAt),
    model: { nx: g.nx, ny: g.ny, cells: g.nx * g.ny, cellSizeM: g.cellSize, extentM: s.extent, ...(s.options.tier ? { tier: s.options.tier } : {}), durationS: s.duration, startTime: s.startTime },
    warnings: i.warnings,
    reproduce: {
      scenarioId: s.id,
      seed: s.options.seed,
      centre: { ...s.origin },
      bbox: [extent.west, extent.south, extent.east, extent.north],
      extentM: s.extent,
      cellSizeM: g.cellSize,
      startTime: s.startTime,
      durationS: s.duration,
      weatherMode: i.req.weather.kind,
      ...(i.req.demoSiteId ? { demoSiteId: i.req.demoSiteId } : {}),
      online: i.req.online,
    },
    workingMemory: workingMemoryForScenario(s),
  });
  return { datasets: records, summary };
}
