/**
 * Shared helpers of the data-set record builders (datasetRecords*.ts): providers and licences (the documented static
 * facts), ledger-to-sizes conversion, extents, and the record skeleton.
 */
import { LocalProjection } from '../core/geo';
import type {
  DatasetEndpoint,
  DatasetExtent,
  DatasetLink,
  DatasetOrigin,
  DatasetRecord,
  DatasetSizes,
  DatasetVintage,
} from '../core/datasets';
import type { LatLon } from '../core/types';
import type { BundleManifest, DatasetLedger, LedgerTotals } from '../data';

// ─────────────────────────────────────────────────────────────────────────────
// Static facts: providers and licences (documented in docs/research/08 and the services' own metadata)
// ─────────────────────────────────────────────────────────────────────────────

export const CC_BY_4: DatasetLink = { name: 'CC BY 4.0', url: 'https://creativecommons.org/licenses/by/4.0/' };

export const PROVIDERS = {
  spatial: { name: 'NSW Spatial Services (Department of Customer Service)', url: 'https://www.spatial.nsw.gov.au/' },
  dccceew: { name: 'NSW Department of Climate Change, Energy, the Environment and Water (DCCEEW)', url: 'https://www.environment.nsw.gov.au/' },
  npws: { name: 'NSW National Parks and Wildlife Service (DCCEEW)', url: 'https://www.nationalparks.nsw.gov.au/' },
  planning: { name: 'NSW Department of Planning, Housing and Infrastructure', url: 'https://www.planning.nsw.gov.au/' },
  awsTerrain: { name: 'Mapzen Terrain Tiles on AWS Open Data (SRTM, U.S. Geological Survey)', url: 'https://registry.opendata.aws/terrain-tiles/' },
  meta: { name: 'Meta and World Resources Institute (WRI)', url: 'https://registry.opendata.aws/dataforgood-fb-forests/' },
  openMeteo: { name: 'Open-Meteo', url: 'https://open-meteo.com/' },
  app: { name: 'FireSim (this app)' },
  user: { name: 'You (entered in the app)' },
} as const satisfies Record<string, DatasetLink>;

export const LICENCES = {
  ccBy: CC_BY_4,
  publicDomain: { name: 'Public domain (SRTM); tiles distributed under AWS Open Data terms', url: 'https://github.com/tilezen/joerd/blob/master/docs/attribution.md' },
  openMeteo: { name: 'CC BY 4.0 (Open-Meteo API data; free for non-commercial use, which includes education)', url: 'https://open-meteo.com/en/license' },
  app: { name: 'Generated by FireSim (no third-party data)' },
  user: { name: 'Entered by the user' },
} as const satisfies Record<string, DatasetLink>;

export const ATTRIBUTION = {
  spatial: '© Spatial Services NSW (CC BY 4.0)',
  imagery: '© State of New South Wales (Spatial Services, a business unit of the Department of Customer Service NSW), CC BY 4.0',
  terrarium: 'Terrain: SRTM data courtesy of the U.S. Geological Survey, tiles by Mapzen on AWS Open Data',
  svtm: '© State of NSW and Department of Climate Change, Energy, the Environment and Water (CC BY 4.0)',
  npws: '© State of NSW and Department of Climate Change, Energy, the Environment and Water (CC BY 4.0)',
  meta: 'Meta and World Resources Institute (WRI) – 2024. High Resolution Canopy Height Maps (CHM). Source imagery for CHM © 2016 Maxar (CC BY 4.0)',
  openMeteo: 'Weather data by Open-Meteo.com (CC BY 4.0), from national weather services and Copernicus ERA5',
  app: 'FireSim',
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// Sizes from the ledger
// ─────────────────────────────────────────────────────────────────────────────

/** Add up the ledger totals of several tags (a data set may use more than one). */
export function sumTotals(ledger: DatasetLedger | undefined, tags: readonly string[]): LedgerTotals {
  const out = ledger?.totals('\u0000none') ?? emptyTotals();
  if (!ledger) return out;
  for (const tag of tags) {
    const t = ledger.totals(tag);
    out.requests += t.requests;
    out.failures += t.failures;
    out.bytes += t.bytes;
    out.bodyBytes += t.bodyBytes;
    out.networkBytes += t.networkBytes;
    out.cacheBytes += t.cacheBytes;
    out.packBytes += t.packBytes;
    out.bundledBytes += t.bundledBytes;
    out.retries += t.retries;
    out.sumMs += t.sumMs;
    for (const k of Object.keys(out.bySource) as (keyof LedgerTotals['bySource'])[]) out.bySource[k] += t.bySource[k];
    out.firstAt = out.firstAt && t.firstAt ? Math.min(out.firstAt, t.firstAt) : out.firstAt || t.firstAt;
    out.lastEndAt = Math.max(out.lastEndAt, t.lastEndAt);
    out.wallMs = out.lastEndAt - out.firstAt;
    out.oldestCachedAt = out.oldestCachedAt && t.oldestCachedAt ? Math.min(out.oldestCachedAt, t.oldestCachedAt) : out.oldestCachedAt || t.oldestCachedAt;
    out.newestCachedAt = Math.max(out.newestCachedAt, t.newestCachedAt);
    out.newestNetworkAt = Math.max(out.newestNetworkAt, t.newestNetworkAt);
    out.storedBytes += t.storedBytes;
  }
  return out;
}

function emptyTotals(): LedgerTotals {
  return {
    requests: 0, failures: 0, bytes: 0, bodyBytes: 0, networkBytes: 0, cacheBytes: 0, packBytes: 0, bundledBytes: 0,
    bySource: { network: 0, cache: 0, stale: 0, pack: 0, bundled: 0 }, retries: 0, sumMs: 0, wallMs: 0, firstAt: 0, lastEndAt: 0,
    oldestCachedAt: 0, newestCachedAt: 0, newestNetworkAt: 0, storedBytes: 0,
  };
}

/** DatasetSizes from ledger totals plus what the loader knows. Bundled bytes are in `transferredBytes` only. */
export function sizesOf(t: LedgerTotals, extra: Partial<DatasetSizes> = {}): DatasetSizes {
  return {
    transferredBytes: t.bytes,
    networkBytes: t.networkBytes,
    cachedBytes: t.cacheBytes + t.packBytes,
    requests: t.requests,
    ...(t.storedBytes > 0 ? { storedOnDeviceBytes: t.storedBytes } : {}),
    ...extra,
  };
}

/** Total byte length of typed arrays / buffers (undefined entries count 0). */
export function typedBytes(...arrays: (ArrayBufferView | ArrayBuffer | undefined | null)[]): number {
  let n = 0;
  for (const a of arrays) if (a) n += a.byteLength;
  return n;
}

/** Typed-array memory of an object's own array properties (one level). */
export function ownArrayBytes(o: object, skip: readonly string[] = []): number {
  let n = 0;
  for (const [k, v] of Object.entries(o)) if (!skip.includes(k) && ArrayBuffer.isView(v)) n += v.byteLength;
  return n;
}

/** Main-thread copy plus the worker's structured-clone copy (src/sim/client.ts posts the scenario without a transfer list). */
export const COPIES = 2;

// ─────────────────────────────────────────────────────────────────────────────
// Geometry, time, endpoints
// ─────────────────────────────────────────────────────────────────────────────

/** WGS84 box and area of the square of side `extentM` around `centre`. */
export function extentOf(centre: LatLon, extentM: number): DatasetExtent {
  const p = new LocalProjection(centre);
  const h = extentM / 2;
  const sw = p.toLatLon(-h, -h);
  const ne = p.toLatLon(h, h);
  const r = (v: number): number => Math.round(v * 1e6) / 1e6;
  return { west: r(sw.lon), south: r(sw.lat), east: r(ne.lon), north: r(ne.lat), areaKm2: Math.round(((extentM * extentM) / 1e6) * 100) / 100 };
}

/** Epoch ms of an ISO date at 00:00 UTC, or 0. */
export const dateMs = (iso: string | undefined): number => {
  if (!iso) return 0;
  const t = Date.parse(/^\d{4}-\d{2}-\d{2}$/.test(iso) ? `${iso}T00:00:00Z` : iso);
  return Number.isFinite(t) ? t : 0;
};

export function endpoint(host: string, path: string, note?: string, requests?: number): DatasetEndpoint {
  return { host, path, ...(note ? { note } : {}), ...(requests !== undefined ? { requests } : {}) };
}

/** Endpoints a tag used, as DatasetEndpoints (from the ledger). */
export function endpointsOf(ledger: DatasetLedger | undefined, tags: readonly string[], note?: string): DatasetEndpoint[] {
  const out: DatasetEndpoint[] = [];
  for (const tag of tags) for (const e of ledger?.endpoints(tag) ?? []) out.push({ host: e.host, path: e.path, requests: e.requests, ...(note ? { note } : {}) });
  return out;
}

/** The size of a bundled file per the manifest or, failing that, the ledger. */
export const bundleBytes = (m: BundleManifest | null | undefined, siteId: string, name: string): number | undefined => m?.sites[siteId]?.files[name]?.bytes;

// ─────────────────────────────────────────────────────────────────────────────
// Vintage helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Vintage of data obtained live (this build), from a stored copy, or bundled. */
export function vintageFor(origin: DatasetOrigin, t: LedgerTotals, now: number, o: { capturedOn?: string; capturedNote?: string; bundleCapturedOn?: string; version?: string; versionNote?: string; currentTo?: string; cacheFreshUntil?: number; packCreatedAt?: number } = {}): DatasetVintage {
  const v: DatasetVintage = { retrievedAt: now, retrievedBasis: 'this-build' };
  if (origin === 'live') {
    v.retrievedAt = t.newestNetworkAt || now;
  } else if (origin === 'cache' || origin === 'area-pack') {
    v.retrievedAt = t.oldestCachedAt || o.packCreatedAt || 0;
    v.retrievedBasis = v.retrievedAt ? 'stored-copy' : 'unknown';
  } else if (origin === 'bundled') {
    v.retrievedAt = dateMs(o.bundleCapturedOn);
    v.retrievedBasis = v.retrievedAt ? 'bundle-capture' : 'unknown';
  } else if (origin === 'none') {
    v.retrievedAt = 0;
    v.retrievedBasis = 'unknown';
  } else {
    v.retrievedBasis = 'generated';
  }
  if (o.capturedOn) v.capturedOn = o.capturedOn;
  if (o.capturedNote) v.capturedNote = o.capturedNote;
  if (o.version) v.version = o.version;
  if (o.versionNote) v.versionNote = o.versionNote;
  if (o.currentTo) v.currentTo = o.currentTo;
  if (o.cacheFreshUntil) v.cacheFreshUntil = o.cacheFreshUntil;
  return v;
}

/** The record skeleton with empty lists; builders fill in the rest. */
export function skeleton(r: Pick<DatasetRecord, 'id' | 'role' | 'title' | 'what' | 'why' | 'provider' | 'licence' | 'attribution' | 'format' | 'kind' | 'status' | 'origin' | 'vintage' | 'coverage' | 'sizes' | 'evidence'> & Partial<DatasetRecord>): DatasetRecord {
  return { endpoints: [], sourceServices: [], stats: [], warnings: [], limitations: [], ...r };
}

/** A month/day-free ISO day of an epoch ms, '' when unknown. */
export const day = (ms: number): string => (ms > 0 ? new Date(ms).toISOString().slice(0, 10) : '');

/** "1 h", "3 days" style age from epoch ms. */
export function ageText(thenMs: number, nowMs: number): string {
  const h = Math.max(0, (nowMs - thenMs) / 3.6e6);
  if (h < 1) return `${Math.max(1, Math.round(h * 60))} min`;
  if (h < 48) return `${Math.round(h)} h`;
  return `${Math.round(h / 24)} days`;
}

/** Share (0-1) of the square (centre, side) that lies inside the square (c2, side2) (flat-earth, domain-sized squares). */
export function overlapShare(centre: LatLon, side: number, c2: LatLon, side2: number): number {
  const ky = 111195;
  const kx = ky * Math.cos((c2.lat * Math.PI) / 180);
  const dx = Math.abs((centre.lon - c2.lon) * kx);
  const dy = Math.abs((centre.lat - c2.lat) * ky);
  const ox = Math.max(0, Math.min(side / 2 + side2 / 2 - dx, side, side2));
  const oy = Math.max(0, Math.min(side / 2 + side2 / 2 - dy, side, side2));
  return Math.max(0, Math.min(1, (ox * oy) / (side * side)));
}
